queue_rules:
  - name: duplicated default from Automatically merge on CI success and review approval
    queue_conditions:
      - base~=main|integ-tests
      - "#approved-reviews-by>=1"
      - approved-reviews-by=@aws-actions/aws-ecr
      - -approved-reviews-by~=author
      - status-success=Run Unit Tests
      - status-success=Semantic Pull Request
      - label!=work-in-progress
      - -title~=(WIP|wip)
      - -merged
      - -closed
      - author!=dependabot[bot]
    merge_conditions:
      # Conditions to get out of the queue (= merged)
      - status-success=Run Unit Tests
      - status-success=Semantic Pull Request
    merge_method: squash
  - name: duplicated default from Automatically approve and merge Dependabot PRs
    queue_conditions:
      - base=main
      - author=dependabot[bot]
      - status-success=Run Unit Tests
      - status-success=Semantic Pull Request
      - -title~=(WIP|wip)
      - -label~=(blocked|do-not-merge)
      - -merged
      - -closed
    merge_conditions:
      # Conditions to get out of the queue (= merged)
      - status-success=Run Unit Tests
      - status-success=Semantic Pull Request
    merge_method: squash

pull_request_rules:
  - name: Automatically approve and merge Dependabot PRs
    conditions:
      - base=main
      - author=dependabot[bot]
      - status-success=Run Unit Tests
      - status-success=Semantic Pull Request
      - -title~=(WIP|wip)
      - -label~=(blocked|do-not-merge)
      - -merged
      - -closed
    actions:
      review:
        type: APPROVE
  - name: Automatically approve and merge Dependabot PRs + Automatically merge on
      CI success and review approval
    conditions: []
    actions:
      queue:
