on:
  push:
    branches:
      - integ-tests

name: Integration Test

jobs:
  job1:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Print current build ID
      run: |
        echo Integration test run: BUILD_ID

    - name: Configure AWS credentials
      id: configure-aws-credentials-us-west-2
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Tag and push a docker image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: github-actions-amazon-ecr-login-integ-tests
        IMAGE_TAG: latest
      run: |
        docker pull amazonlinux
        docker tag amazonlinux $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Login to Amazon ECR using explicit registry ID
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registries: ${{ steps.configure-aws-credentials.outputs.aws-account-id }}

    - name: Configure AWS credentials
      id: configure-aws-credentials-us-east-1
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR Public
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry-type: public

    - name: Tag and push a docker image to Amazon ECR Public
      env:
        ECR_PUBLIC_REGISTRY_ALIAS: github-actions-amazon-ecr-login-integ-tests
        ECR_PUBLIC_REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
        ECR_PUBLIC_REPOSITORY: github-actions-amazon-ecr-login-integ-tests
        IMAGE_TAG: latest
      run: |
        docker pull amazonlinux
        docker tag amazonlinux $ECR_PUBLIC_REGISTRY/$ECR_PUBLIC_REGISTRY_ALIAS/$ECR_PUBLIC_REPOSITORY:$IMAGE_TAG
        docker push $ECR_PUBLIC_REGISTRY/$ECR_PUBLIC_REGISTRY_ALIAS/$ECR_PUBLIC_REPOSITORY:$IMAGE_TAG
    outputs:
      docker_username: ${{ steps.login-ecr.outputs.docker_username_386586417298_dkr_ecr_us_west_2_amazonaws_com }}
      docker_password: ${{ steps.login-ecr.outputs.docker_password_386586417298_dkr_ecr_us_west_2_amazonaws_com }}

  job2:
    name: Service
    needs: job1
    runs-on: ubuntu-latest
    services:
      internal-service:
        image: 386586417298.dkr.ecr.us-west-2.amazonaws.com/github-actions-amazon-ecr-login-integ-tests:latest
        credentials:
          username: ${{ needs.job1.outputs.docker_username }}
          password: ${{ needs.job1.outputs.docker_password }}
        ports:
          - '80:80'
    steps:
      - name: Echo
        run: echo "Integration Test"
